#!/usr/bin/env bash
# Parallel-swimlane agent workspace: shared plan-state table + async sticky
# notes (v1.2.0 协同 agent workspace). Sources lib.sh (as_lock single lock,
# as_now_iso timestamp, as_cell escaping, as_atomic_write mv, LC_ALL=C,
# bash-3.1 gate — all inherited). One deliberate platform branch, in lib.sh's
# dual-fallback idiom: the MERGELOCK stamp parser tries BSD `date -j -f`
# first, then falls back to GNU `date -d`.
#
# Usage:
#   parallel-workspace.sh --init <plan_id> <plan_desc> [any_info]
#       Register a plan row (state=doing). Duplicate id -> error, non-zero.
#   parallel-workspace.sh --remove <plan_id>
#       Delete the plan row; cascade: clears ALL of the plan's MSG rows (sent
#       src==id AND received dst==id) and strips blank lines.
#   parallel-workspace.sh --show [--state doing|test|merge] [--plan <id>]
#       Print PLAN rows, optionally filtered. Reads also run inside the lock
#       (one lock covers the whole run, so --show sees a consistent snapshot).
#   parallel-workspace.sh --update <plan_id> [--any_info xxx] [--state doing|test] [--plan_desc xxx]
#       Rewrite fields (any subset, >=1 required). --state merge is FORBIDDEN
#       here — merge is entered only via --merge (rollback path: --state doing).
#       Auto-returns the plan's inbox afterwards (same output as --recv <id>).
#   parallel-workspace.sh --merge <plan_id>
#       Merge-state exclusivity, see the iron law below. Auto-returns the
#       inbox too. Self already merge -> idempotent success.
#   parallel-workspace.sh --send --src <id> --dst <id|all> --msg xxx
#       Append a MSG row (time generated by as_now_iso, UTC ISO-8601).
#   parallel-workspace.sh --recv <id>
#       Print every MSG row addressed to <id> or broadcast (dst==all).
#       --revc is a compatibility alias.
#   parallel-workspace.sh --withdraw <plan_id>
#       Remove the plan's sent MSG rows (src==id); strips blank lines.
#
# Data file: $AS_ROOT/.agentspace-parallel-workspace.txt (inside the AGENTSPACE
# ledger; MUST stay gitignored — the .gitignore entry ships with the release
# material wave, not with this script; this script performs NO git operations).
# Line-oriented, '|'-separated; free text (desc/info/msg) is escaped on write
# via lib.sh as_cell ('|'->'\|', newline/tab->space, CR dropped) and presented
# verbatim on read:
#   PLAN|<plan_id>|<state>|<plan_desc>|<any_info>     plan_id numeric, 0001-form (as_norm_id); state in {doing,test,merge}
#   MSG|<src_plan_id>|<dst_plan_id|all>|<iso_time>|<msg>
#
# Lock semantics: ONE as_lock file lock taken at script start covers every
# operation of the run; the lib.sh EXIT trap releases it. No second lock, no
# lock polling. Every write path is:
#   lock -> read whole file -> transform -> mktemp -> atomic mv -> (trap) release
# never append-in-place. Single blank-line strip point: every write pipeline
# ends in `awk 'NF'` — a post-write file never contains blank lines.
# The ONLY release-before-exit is the --merge occupied path: it drops the lock
# (same ownership-guarded teardown as the lib.sh trap), sleeps 60s ONCE, then
# re-acquires the SAME single lock via as_lock (stale-lock takeover stays
# as_lock's job) and re-checks the freshly re-read table once: freed ->
# proceed; still occupied -> report the occupier, exit non-zero. No polling.
#
# 短窗铁律: merge 态在表内存留时间必须尽可能短。--merge only flips the table
# row and returns; the caller (agent) performs the real merge OUTSIDE the
# table, then MUST immediately either
#   --remove <id>                  (merge landed -> free the slot; cascades MSG cleanup)
#   --update <id> --state doing    (merge aborted -> roll back)
# At most ONE plan may hold state==merge at any time.
#
# Existence discipline: ids are normalized via as_norm_id (numeric, %04d).
# --update / --merge / --remove / --withdraw / --send --src must reference
# REGISTERED plan ids; --send --dst accepts `all` or a registered id;
# violations exit non-zero.
# Exit codes: 0 = ok; 1 = operational failure (duplicate init / unregistered
# id / forbidden state / merge slot still occupied after the 60s re-check);
# 3 = usage error (bad arity / unknown option / missing value / free-text
# field ending with a backslash).
set -euo pipefail
source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

WS_FILE="$AS_ROOT/.agentspace-parallel-workspace.txt"

# as_now_iso comes from lib.sh when present; this fallback keeps the script
# self-sufficient on workspaces whose lib.sh predates it (same call shape).
declare -F as_now_iso >/dev/null 2>&1 || as_now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ; }

ws_usage() {
  cat >&2 <<'EOF'
usage: parallel-workspace.sh <subcommand> [args]
  --init <plan_id> <plan_desc> [any_info]           register plan (state=doing; duplicate id -> error)
  --remove <plan_id>                                remove plan + cascade-clear all its MSG rows
  --show [--state doing|test|merge] [--plan <id>]   print plan rows (filterable)
  --update <plan_id> [--any_info x] [--state doing|test] [--plan_desc x]
                                                    state=merge forbidden here; auto-returns the inbox
  --merge <plan_id>                                 exclusive merge slot (60s single recheck; auto-returns the inbox)
  --send --src <id> --dst <id|all> --msg xxx        append a message row
  --recv <id>                                       print inbox (dst==id or dst==all); --revc 兼容别名
  --withdraw <plan_id>                              remove the plan's sent MSG rows (src==id)
EOF
}
ws_usage_err() {
  printf 'error: %s\n' "$*" >&2
  ws_usage
  exit 3
}

# Free-text fields must not END with a backslash: rows are built without cell
# padding, so a trailing '\' fuses with the following '|' separator into a
# literal \| escape — ws_field's shield then eats the separator and silently
# merges the desc/info columns on the next read-modify-write. info and msg are
# last fields today (nothing follows them) — refused too, as insurance against
# a future row format adding a field after them.
ws_cell_check() {  # <value> <field-label>
  case "$1" in
    *\\) ws_usage_err "$2 must not end with a backslash — it would fuse with the row's | separator into a literal \\| escape (drop the trailing backslash and retry)" ;;
  esac
}

# ---- read helpers (all run inside the one lock — consistency snapshot) ----

# Nth '|'-field of the PLAN row with id <id> ('\|' shielded before the split
# and restored verbatim — same discipline as lib.sh as_row_cell — so a desc or
# info containing an escaped pipe cannot shift the column positions).
ws_field() {
  local esc
  [ -f "$WS_FILE" ] || return 0
  esc="$(printf '\037')"
  sed "s/\\\\|/$esc/g" "$WS_FILE" | awk -F'|' -v id="$1" -v c="$2" -v esc="$esc" '
    $1 == "PLAN" && $2 == id { v = $c; gsub(esc, "\\|", v); print v; exit }
  '
}
ws_plan_state() { ws_field "$1" 3; }
ws_plan_exists() { [ -n "$(ws_plan_state "$1")" ]; }

# The merge-slot occupier: first PLAN row other than <self> holding
# state==merge; empty when the slot is free. Prefix fields (PLAN|<digits>|)
# never contain escapes, so the plain split is safe for the match.
ws_merge_occupant() {
  [ -f "$WS_FILE" ] || return 0
  ID="$1" awk -F'|' '
    $1 == "PLAN" && $3 == "merge" && $2 != ENVIRON["ID"] { print $2; exit }
  ' "$WS_FILE" || true
}

# Stale-merge takeover (expert review, wedge fix): a merge state is held by an
# agent, not a process — the agent may die between --merge and --remove, wedging
# the slot forever (the lock layer has stale recovery; the table layer must too).
# --merge stamps MERGELOCK|<id>|<utc-iso>; an occupant whose stamp is older than
# the threshold is auto-reverted to doing on next --merge, with a warning. The
# stamp row rides the same lock + atomic-write pipeline (no new race). The
# window runs from the holder's LAST merge activity — every --merge re-stamps
# (first entry and idempotent re-entry alike), so the threshold detects a dead
# holder and never caps a live, busy merge.
MERGE_STALE_SECONDS=900   # 15 min: a merge window is seconds-to-minutes by the 短窗铁律
ws_now_epoch() { date -u +%s; }
ws_merge_stamp_epoch() {  # <id> -> epoch or empty
  [ -f "$WS_FILE" ] || return 0
  ID="$1" awk -F'|' '$1 == "MERGELOCK" && $2 == ENVIRON["ID"] { print $3; exit }' "$WS_FILE" \
    | { IFS= read -r iso || true
        [ -n "${iso:-}" ] || return 0
        date -u -j -f "%Y-%m-%dT%H:%M:%SZ" "$iso" +%s 2>/dev/null \
          || date -u -d "$iso" +%s 2>/dev/null || true
      }
}
ws_set_merge_stamp() {  # <id>  (replace-or-append, same lock + atomic pipeline)
  local tmp iso; iso="$(as_now_iso)"
  tmp="$(mktemp "$AS_TMPDIR/tmp.XXXXXXXX")"
  ID="$1" ISO="$iso" awk -F'|' '
    BEGIN { done = 0 }
    $1 == "MERGELOCK" && $2 == ENVIRON["ID"] { print "MERGELOCK|" ENVIRON["ID"] "|" ENVIRON["ISO"]; done = 1; next }
    { print }
    END { if (!done) print "MERGELOCK|" ENVIRON["ID"] "|" ENVIRON["ISO"] }
  ' "$WS_FILE" | awk 'NF' > "$tmp"
  as_atomic_write "$WS_FILE" "$tmp"
}
ws_clear_merge_stamp() {  # <id>
  local tmp
  tmp="$(mktemp "$AS_TMPDIR/tmp.XXXXXXXX")"
  ID="$1" awk -F'|' '$1 == "MERGELOCK" && $2 == ENVIRON["ID"] { next } { print }' "$WS_FILE" | awk 'NF' > "$tmp"
  as_atomic_write "$WS_FILE" "$tmp"
}

# PLAN rows through the --show filters (state and/or id); lines verbatim.
ws_print_plans() {
  [ -f "$WS_FILE" ] || return 0
  ST="$1" PID="$2" awk -F'|' '
    $1 != "PLAN" { next }
    ENVIRON["ST"] != ""  && $3 != ENVIRON["ST"]  { next }
    ENVIRON["PID"] != "" && $2 != ENVIRON["PID"] { next }
    { print }
  ' "$WS_FILE" || true
}

# MSG rows addressed to <id> or broadcast (dst==all); lines verbatim.
ws_recv_rows() {
  [ -f "$WS_FILE" ] || return 0
  ID="$1" awk -F'|' '
    $1 == "MSG" && ($3 == ENVIRON["ID"] || $3 == "all") { print }
  ' "$WS_FILE" || true
}

# Count MSG rows for <id> by mode: src (sent), dst (inbox incl. all), both
# (the --remove cascade surface).
ws_count_msgs() {
  [ -f "$WS_FILE" ] || { printf '0\n'; return 0; }
  MODE="$1" ID="$2" awk -F'|' '
    $1 != "MSG" { next }
    ENVIRON["MODE"] == "src"  && $2 == ENVIRON["ID"] { c++; next }
    ENVIRON["MODE"] == "dst"  && ($3 == ENVIRON["ID"] || $3 == "all") { c++; next }
    ENVIRON["MODE"] == "both" && ($2 == ENVIRON["ID"] || $3 == ENVIRON["ID"]) { c++; next }
    END { print c + 0 }
  ' "$WS_FILE" 2>/dev/null || printf '0\n'
}

# ---- write helpers (lock held; read-all -> transform -> tmp -> atomic mv) ----

# Append a pre-built row (WS_ROW, stored-escape form). Full read + append +
# blank strip, atomic mv — never `>>` in place.
ws_append_row() {
  local tmp
  tmp="$(mktemp "$AS_TMPDIR/tmp.XXXXXXXX")"
  chmod 644 "$tmp" 2>/dev/null || true
  { cat "$WS_FILE" 2>/dev/null || true; printf '%s\n' "$WS_ROW"; } | awk 'NF' > "$tmp"
  as_atomic_write "$WS_FILE" "$tmp"
}

# Replace the PLAN row of WS_ID with the pre-built row WS_ROW (rows travel via
# the environment, never -v — lib.sh's rule, so stored '\|' escapes survive).
# Every other line passes through byte-identical.
ws_replace_plan_row() {
  local tmp
  tmp="$(mktemp "$AS_TMPDIR/tmp.XXXXXXXX")"
  WS_ID="$1" WS_ROW="$WS_ROW" awk -F'|' '
    $1 == "PLAN" && $2 == ENVIRON["WS_ID"] { print ENVIRON["WS_ROW"]; next }
    { print }
  ' "$WS_FILE" | awk 'NF' > "$tmp"
  as_atomic_write "$WS_FILE" "$tmp"
}

# --remove surface: drop the PLAN row and ALL of the plan's MSG rows (sent
# src==id and received dst==id — 清其全部 MSG 行).
ws_remove_plan() {
  local tmp
  tmp="$(mktemp "$AS_TMPDIR/tmp.XXXXXXXX")"
  ID="$1" awk -F'|' '
    $1 == "PLAN" && $2 == ENVIRON["ID"] { next }
    $1 == "MSG" && ($2 == ENVIRON["ID"] || $3 == ENVIRON["ID"]) { next }
    { print }
  ' "$WS_FILE" | awk 'NF' > "$tmp"
  as_atomic_write "$WS_FILE" "$tmp"
}

# --withdraw surface: drop every MSG row sent by <id> (src==id).
ws_withdraw_msgs() {
  local tmp
  tmp="$(mktemp "$AS_TMPDIR/tmp.XXXXXXXX")"
  ID="$1" awk -F'|' '
    $1 == "MSG" && $2 == ENVIRON["ID"] { next }
    { print }
  ' "$WS_FILE" | awk 'NF' > "$tmp"
  as_atomic_write "$WS_FILE" "$tmp"
}

# Release the as_lock lock for the --merge wait window: identical teardown to
# the lib.sh EXIT trap (tmp dir + ownership-guarded lock removal — a waiter
# whose lock was stale-taken-over can never delete the new holder's lock),
# then clear the trap so an interrupt mid-sleep has no lock side effects. The
# single lock is re-acquired with as_lock afterwards.
ws_unlock_for_wait() {
  rm -rf "${AS_TMPDIR:-}" 2>/dev/null || true
  if [ "$(cat "$AS_ROOT/.scripts.lock/pid" 2>/dev/null || true)" = "$$" ]; then
    rm -rf "$AS_ROOT/.scripts.lock" 2>/dev/null || true
  fi
  trap - EXIT
  unset AS_TMPDIR
}

ws_print_inbox() {  # <id> <reason-label>
  local rows n
  rows="$(ws_recv_rows "$1")"
  n="$(ws_count_msgs dst "$1")"
  if [ "$n" -eq 0 ]; then
    printf '== inbox of %s%s: 0 message(s) ==\n' "$1" "${2:+ ($2)}"
  else
    printf '== inbox of %s%s: %d message(s) ==\n%s\n' "$1" "${2:+ ($2)}" "$n" "$rows"
  fi
}

ws_require_plan() {  # <id> <context>
  ws_plan_exists "$1" || { printf 'error: plan not registered: %s (%s)\n' "$1" "$2" >&2; exit 1; }
}

# ---- subcommand bodies (dispatched inside the lock) ----

op_init() {  # <id> <desc> <info>
  local row
  if ws_plan_exists "$1"; then
    printf 'error: plan already registered: %s (duplicate --init; use --update)\n' "$1" >&2
    exit 1
  fi
  row="PLAN|$1|doing|$(as_cell "$2")|$(as_cell "$3")"
  WS_ROW="$row" ws_append_row
  printf 'registered: %s\n' "$row"
}

op_remove() {  # <id>
  local n
  ws_require_plan "$1" "--remove"
  n="$(ws_count_msgs both "$1")"
  ws_remove_plan "$1"
  ws_clear_merge_stamp "$1"   # releasing the slot also drops its merge stamp
  if [ "$n" -gt 0 ]; then
    printf 'removed: plan %s (+%d message row(s) cascaded: sent src==%s and received dst==%s)\n' "$1" "$n" "$1" "$1"
  else
    printf 'removed: plan %s\n' "$1"
  fi
}

op_show() {  # <state-filter> <id-filter>
  local rows label
  rows="$(ws_print_plans "$1" "$2")"
  label=""
  if [ -n "$1" ] || [ -n "$2" ]; then
    label=" (state=${1:-*} plan=${2:-*})"
  fi
  if [ -z "$rows" ]; then
    printf '== plans%s: 0 row(s) ==\n' "$label"
  else
    printf '== plans%s ==\n%s\n' "$label" "$rows"
  fi
}

op_update() {  # <id>; field overrides in U_* (U_*_SET flags)
  local cur_state cur_desc cur_info new_state new_desc new_info row
  ws_require_plan "$1" "--update"
  cur_state="$(ws_field "$1" 3)"
  cur_desc="$(ws_field "$1" 4)"
  cur_info="$(ws_field "$1" 5)"
  new_state="$cur_state"; new_desc="$cur_desc"; new_info="$cur_info"
  # Current desc/info arrive already in stored-escape form (ws_field restores
  # verbatim) — passed through unchanged; only caller-provided values go
  # through as_cell. Never re-escape an escaped value.
  if [ "$U_DESC_SET" -eq 1 ]; then new_desc="$(as_cell "$U_DESC")"; fi
  if [ "$U_INFO_SET" -eq 1 ]; then new_info="$(as_cell "$U_INFO")"; fi
  if [ "$U_STATE_SET" -eq 1 ]; then new_state="$U_STATE"; fi
  row="PLAN|$1|$new_state|$new_desc|$new_info"
  WS_ROW="$row" ws_replace_plan_row "$1"
  # Rolling back (or re-confirming) out of merge releases the slot: drop the stamp.
  [ "$new_state" != "merge" ] && ws_clear_merge_stamp "$1"
  printf 'updated: %s\n' "$row"
  ws_print_inbox "$1" "auto-return after --update"
}

op_merge() {  # <id>
  local occupant row cur_desc cur_info
  ws_require_plan "$1" "--merge"
  if [ "$(ws_plan_state "$1")" = "merge" ]; then
    ws_set_merge_stamp "$1"   # renewal: the stale window runs from the LAST merge activity — an idempotent re-entry is proof of life
    printf 'already merge: plan %s (idempotent, merge window renewed — 短窗铁律: finish the real merge, then --remove %s)\n' "$1" "$1"
    ws_print_inbox "$1" "auto-return after --merge"
    return 0
  fi
  occupant="$(ws_merge_occupant "$1")"
  if [ -n "$occupant" ]; then
    # Stale-merge takeover: if the occupant's stamp is older than the
    # threshold, its agent died mid-merge — revert it to doing in-lock, warn,
    # and treat the slot as free (no wait needed).
    local stamp now age
    stamp="$(ws_merge_stamp_epoch "$occupant")"
    now="$(ws_now_epoch)"
    if [ -n "$stamp" ] && [ $((now - stamp)) -gt "$MERGE_STALE_SECONDS" ]; then
      printf 'warning: merge slot held by plan %s is stale (>%ss — occupier likely died mid-merge); reverting %s to doing and proceeding\n' "$occupant" "$MERGE_STALE_SECONDS" "$occupant" >&2
      local o_desc o_info
      o_desc="$(ws_field "$occupant" 4)"; o_info="$(ws_field "$occupant" 5)"
      WS_ROW="PLAN|$occupant|doing|$o_desc|$o_info" ws_replace_plan_row "$occupant"
      ws_clear_merge_stamp "$occupant"
      occupant=""
    fi
  fi
  if [ -n "$occupant" ]; then
    # The wait must NOT hold the lock: the occupier's own --remove /
    # --update needs it to free the slot. Drop, sleep 60 once, re-acquire
    # the same single lock, re-check the freshly re-read table once.
    printf 'merge slot occupied by plan %s — releasing lock, sleeping 60s, then re-checking once...\n' "$occupant"
    ws_unlock_for_wait
    sleep 60
    as_lock
    ws_require_plan "$1" "re-check after the 60s merge wait"
    occupant="$(ws_merge_occupant "$1")"
    if [ -n "$occupant" ]; then
      printf 'error: merge slot still occupied by plan %s after the 60s wait — recovery lever: any agent may run `--update %s --state doing` (merge state has no owner check) if the occupier is confirmed dead, or `--remove %s`; otherwise retry --merge later\n' "$occupant" "$occupant" "$occupant" >&2
      exit 1
    fi
    printf 'merge slot freed — proceeding for plan %s\n' "$1"
  fi
  cur_desc="$(ws_field "$1" 4)"
  cur_info="$(ws_field "$1" 5)"
  row="PLAN|$1|merge|$cur_desc|$cur_info"
  WS_ROW="$row" ws_replace_plan_row "$1"
  ws_set_merge_stamp "$1"
  printf 'merge state set: %s\n' "$row"
  printf '短窗铁律: run the real merge OUTSIDE the table NOW, then --remove %s (landed) or --update %s --state doing (aborted)\n' "$1" "$1"
  ws_print_inbox "$1" "auto-return after --merge"
}

op_send() {  # S_SRC / S_DST / S_MSG
  local row
  ws_require_plan "$S_SRC" "--send --src"
  if [ "$S_DST" != "all" ]; then
    ws_require_plan "$S_DST" "--send --dst"
  fi
  row="MSG|$S_SRC|$S_DST|$(as_now_iso)|$(as_cell "$S_MSG")"
  WS_ROW="$row" ws_append_row
  printf 'sent: %s\n' "$row"
}

op_withdraw() {  # <id>
  local n
  ws_require_plan "$1" "--withdraw"
  n="$(ws_count_msgs src "$1")"
  if [ "$n" -eq 0 ]; then
    printf 'withdraw: plan %s has no sent message row(s)\n' "$1"
    return 0
  fi
  ws_withdraw_msgs "$1"
  printf 'withdraw: removed %d sent message row(s) of plan %s\n' "$n" "$1"
}

# ---- argument parsing (pure — no workspace access, runs before the lock) ----

CMD="${1:-}"
[ -n "$CMD" ] || ws_usage_err "missing subcommand"
shift

case "$CMD" in
  --init)
    [ $# -ge 2 ] && [ $# -le 3 ] || ws_usage_err "--init <plan_id> <plan_desc> [any_info]"
    OP_ID="$(as_norm_id "$1")"
    OP_DESC="$2"
    OP_INFO="${3:-}"
    [ -n "$OP_DESC" ] || ws_usage_err "--init needs a non-empty <plan_desc>"
    ws_cell_check "$OP_DESC" "<plan_desc>"
    ws_cell_check "$OP_INFO" "[any_info]"
    ;;
  --remove)
    [ $# -eq 1 ] || ws_usage_err "--remove <plan_id>"
    OP_ID="$(as_norm_id "$1")"
    ;;
  --merge)
    [ $# -eq 1 ] || ws_usage_err "--merge <plan_id>"
    OP_ID="$(as_norm_id "$1")"
    ;;
  --withdraw)
    [ $# -eq 1 ] || ws_usage_err "--withdraw <plan_id>"
    OP_ID="$(as_norm_id "$1")"
    ;;
  --recv|--revc)
    [ $# -eq 1 ] || ws_usage_err "--recv <plan_id> (--revc 兼容别名)"
    OP_ID="$(as_norm_id "$1")"
    ;;
  --show)
    F_STATE=""; F_PLAN=""
    while [ $# -gt 0 ]; do
      case "$1" in
        --state)
          [ $# -ge 2 ] || ws_usage_err "--state needs a value"
          case "$2" in
            doing|test|merge) ;;
            *) ws_usage_err "--state must be doing|test|merge (got: $2)" ;;
          esac
          F_STATE="$2"; shift 2
          ;;
        --plan)
          [ $# -ge 2 ] || ws_usage_err "--plan needs a value"
          F_PLAN="$(as_norm_id "$2")"; shift 2
          ;;
        *) ws_usage_err "unknown --show option: $1" ;;
      esac
    done
    ;;
  --update)
    [ $# -ge 1 ] || ws_usage_err "--update <plan_id> [--any_info xxx] [--state doing|test] [--plan_desc xxx]"
    OP_ID="$(as_norm_id "$1")"; shift
    U_INFO=""; U_STATE=""; U_DESC=""; U_INFO_SET=0; U_STATE_SET=0; U_DESC_SET=0
    while [ $# -gt 0 ]; do
      case "$1" in
        --any_info)
          [ $# -ge 2 ] || ws_usage_err "--any_info needs a value"
          U_INFO="$2"; U_INFO_SET=1; shift 2
          ;;
        --plan_desc)
          [ $# -ge 2 ] || ws_usage_err "--plan_desc needs a value"
          U_DESC="$2"; U_DESC_SET=1; shift 2
          ;;
        --state)
          [ $# -ge 2 ] || ws_usage_err "--state needs a value"
          case "$2" in
            doing|test) U_STATE="$2"; U_STATE_SET=1 ;;
            merge) printf 'error: --update cannot set state=merge — merge 只能由 --merge 进入 (失败回退走 --state doing)\n' >&2; exit 1 ;;
            *) ws_usage_err "--state must be doing|test (got: $2)" ;;
          esac
          shift 2
          ;;
        *) ws_usage_err "unknown --update option: $1" ;;
      esac
    done
    if [ "$U_INFO_SET" -eq 0 ] && [ "$U_STATE_SET" -eq 0 ] && [ "$U_DESC_SET" -eq 0 ]; then
      ws_usage_err "--update needs at least one of --any_info / --state / --plan_desc"
    fi
    if [ "$U_DESC_SET" -eq 1 ]; then ws_cell_check "$U_DESC" "--plan_desc"; fi
    if [ "$U_INFO_SET" -eq 1 ]; then ws_cell_check "$U_INFO" "--any_info"; fi
    ;;
  --send)
    S_SRC=""; S_DST=""; S_MSG=""
    while [ $# -gt 0 ]; do
      case "$1" in
        --src) [ $# -ge 2 ] || ws_usage_err "--src needs a value"; S_SRC="$2"; shift 2 ;;
        --dst) [ $# -ge 2 ] || ws_usage_err "--dst needs a value"; S_DST="$2"; shift 2 ;;
        --msg) [ $# -ge 2 ] || ws_usage_err "--msg needs a value"; S_MSG="$2"; shift 2 ;;
        *) ws_usage_err "unknown --send option: $1" ;;
      esac
    done
    { [ -n "$S_SRC" ] && [ -n "$S_DST" ] && [ -n "$S_MSG" ]; } || ws_usage_err "--send needs --src <id> --dst <id|all> --msg xxx"
    ws_cell_check "$S_MSG" "--msg"
    S_SRC="$(as_norm_id "$S_SRC")"
    [ "$S_DST" = "all" ] || S_DST="$(as_norm_id "$S_DST")"
    ;;
  -h|--help)
    ws_usage
    exit 0
    ;;
  *) ws_usage_err "unknown subcommand: $CMD" ;;
esac

# ---- one lock for the whole run; the lib.sh EXIT trap releases it ----
as_lock

case "$CMD" in
  --init)        op_init "$OP_ID" "$OP_DESC" "$OP_INFO" ;;
  --remove)      op_remove "$OP_ID" ;;
  --show)        op_show "$F_STATE" "$F_PLAN" ;;
  --update)      op_update "$OP_ID" ;;
  --merge)       op_merge "$OP_ID" ;;
  --withdraw)    op_withdraw "$OP_ID" ;;
  --send)        op_send ;;
  --recv|--revc) ws_print_inbox "$OP_ID" "" ;;
esac
